version: '3.7'

networks:
    laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8088:80"
    volumes:

    depends_on:
      -php
      -mysql
    networks:
      -laravel

  mysql:
    networks:
      -laravel

  php:
    networks:
      -laravel
